.github/workflows/deploy-contract.yml, .github/workflows/run-test.yml, deployment/deployRemoteRelay.ts, deployment/swapV2WithRelay.ts, hardhat.config.ts, integrationTest/swapV2.ts, package-lock.json, package.json
Deploy contract using json-rpc-relay
=> Json relay to deploy contract

contracts/AbstractSwap.sol, contracts/mock/MockBaseContract.sol, contracts/test/SwapTest.sol, test/swapv2-test.ts
Test case coverage increased to 96%
=> Update tests to increase branch coverage

contracts/AbstractLPToken.sol, contracts/AbstractSwap.sol, test/swapv2-test.ts
=> spot price presion support

contracts/AbstractLPToken.sol, contracts/AbstractSwap.sol, contracts/ILPToken.sol, contracts/LPToken.sol, contracts/common/IERC20.sol, contracts/mock/ERC20Mock.sol, contracts/test/LPTokenTest.sol, deployment/LPToken.ts, deployment/baseContract.ts, integrationTest/lpToken.ts, integrationTest/swapV2.ts, test/swapv2-test.ts
=> Burn token on remove liquidity

contracts/AbstractSwap.sol, test/swapv2-test.ts
=> token and contract address access method added

contracts/AbstractPair.sol, contracts/Factory.sol, contracts/IPair.sol, test/swapv2-test.ts
=> fee added to pair initializer

contracts/AbstractPair.sol, test/pair-test.ts
=> add fee to pool for tokens

deployment/contract/factory.ts
=> factory contract deployment updated

contracts/AbstractLPToken.sol, contracts/AbstractPair.sol, contracts/Factory.sol, contracts/ILPToken.sol, contracts/LPToken.sol, contracts/Pair.sol, deployment/deployContractOnTestnet.ts, deployment/state/contracts.json, integrationTest/factory.ts, integrationTest/utils/EventConsumer.ts, test/pair-test.ts
This PR Introduces dynamic pair creation ability.
Now we can use the factory to create new Pair contracts for any Token pairs.
=> Dynamic pair new approach

contracts/AbstractPair.sol, contracts/IPair.sol, deployment/state/contracts.json, integrationTest/factory.ts, integrationTest/pair.ts, package-lock.json, test/pair-test.ts
fee transfer to treasury account.
=> fee transfer to treasury

README.md, UPGRADE.md, contracts/Factory.sol, contracts/ILPToken.sol, contracts/IPair.sol, contracts/LPToken.sol, contracts/Pair.sol, contracts/common/BaseHTS.sol, contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/IBaseHTS.sol, contracts/common/IERC20.sol, contracts/common/ProxyPattern.sol, contracts/mock/ERC20Mock.sol, contracts/mock/MockBaseContract.sol
Applied linting across contracts except Hedera owned contracts
=> Applied linting across contracts except Hedera owned contracts

contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/GovernorTokenCreate.sol, deployment/governor.ts, deployment/service/ContractService.ts, deployment/state/contracts.json, integrationTest/governor.ts, test/governer-test.ts
Created Abstract Governor Contract, and separated Create token contract
=> abstract governor created and token create governor added

contracts/common/GovernorTextProposal.sol, deployment/governorTextProposal.ts, deployment/service/ContractService.ts, deployment/state/contracts.json, integrationTest/GovernorMethods.ts, integrationTest/governor.ts, integrationTest/governorTextProposal.ts
=> Create text proposal

contracts/common/GovernorTokenCreate.sol, integrationTest/governor.ts, integrationTest/governorUpgrade.ts
Generate governor token from proposal and create pair with it.
=> Create pair from newly created governor token

.gitignore, contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/GovernorTextProposal.sol, contracts/common/GovernorTokenCreate.sol, contracts/common/GovernorTransferToken.sol, contracts/common/GovernorUpgrade.sol, contracts/mock/ERC20Mock.sol, contracts/mock/IERC20Mock.sol, contracts/mock/MockBaseContract.sol, deployment/state/contracts.json, integrationTest/GovernorMethods.ts, integrationTest/governor.ts, integrationTest/governorTextProposal.ts, integrationTest/governorTransferToken.ts, integrationTest/governorUpgrade.ts, test/governer-test.ts, test/pair-test.ts
Deduction of 1 GOD token on proposal creation and return it back on Execution or Cancel of the proposal complete.
=> Governor contract deduct god

contracts/Factory.sol, deployment/state/contracts.json, integrationTest/factory.ts, test/pair-test.ts
create multiple pairs issue resolved
=> create multiple pairs issue resolved

integrationTest/BaseHTS.ts, integrationTest/factory.ts, integrationTest/governorTextProposal.ts, integrationTest/lpToken.ts, integrationTest/pair.ts
=> refactored integration test

contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/GovernorTokenCreate.sol, deployment/state/contracts.json, integrationTest/governor.ts, package-lock.json, package.json, test/governer-test.ts
Token Create Governor, able to create multiple proposals.
=> Governor single contract logic

contracts/Factory.sol, contracts/IPair.sol, contracts/Pair.sol, contracts/mock/MockBaseContract.sol, integrationTest/factory.ts, integrationTest/pair.ts, test/pair-test.ts
code clean-up for pair contract
=> code clean-up for pair contract

contracts/Factory.sol, integrationTest/factory.ts, integrationTest/utils/arrayUtils.ts, test/pair-test.ts
=> get all pair contracts

.github/workflows/deploy-contract-github.yml, contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/GovernorCountingSimpleUpgradeable.sol, contracts/mock/ERC20Mock.sol, deployment/state/contracts.json, entrypoint.sh, hardhat.config.ts, integrationTest/governorDelegation.ts, integrationTest/utils/utils.ts, test/governer-test.ts
Added delegate governor changes
=> Added delegate governor changes

contracts/common/GovernorCountingSimpleInternal.sol, contracts/common/GovernorTextProposal.sol, contracts/common/GovernorTokenCreate.sol, contracts/common/GovernorTransferToken.sol, contracts/common/GovernorUpgrade.sol, deployment/state/contracts.json, integrationTest/GovernorMethods.ts, integrationTest/governor.ts, integrationTest/governorDelegation.ts, integrationTest/governorTextProposal.ts, integrationTest/governorTransferToken.ts, integrationTest/governorUpgrade.ts, test/governer-test.ts
=> Refactored All Governors 

hardhat.config.ts
changed in optimizer for large contract file deployment.
=> create token governor contract deployment

deployment/state/contracts.json
sync contract address json file
=> sync contract deployed json file

deployment/state/contracts.json
=> json updated.

test/helper.ts, utils/Helper.ts
File path fixes issue came on windows.
=> fixed file path issue came on windows

test/pair-test.ts
=> test commit (#84)

test/pair-test.ts
=> test commit

test/pair-test.ts
=> removed unused code

test/pair-test.ts
=> removed unused code (#93)

contracts/ILPToken.sol, contracts/LPToken.sol, contracts/Pair.sol, deployment/state/contracts.json, integrationTest/factory.ts, test/pair-test.ts
LP token address comes with pair tokens
=> Lp token address expose (#95)

contracts/LPToken.sol, contracts/Pair.sol, contracts/governance/GovernorCountingSimpleInternal.sol, contracts/mock/MockBaseContract.sol, test/governer-test.ts, test/pair-test.ts
Improve test coverage for multiple contracts.
=> Improve test coverage

contracts/governance/GovernorTransferToken.sol, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
added changes for title & link under GovernorTransferToken
=> added changes for title & link under GovernorTransferToken

contracts/governance/GovernorTransferToken.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
=> added changes for title & link under GovernorTransferToken (#97)

integrationTest/governance/governorTransferToken.ts
=> integration test fixed

contracts/governance/GovernorCountingSimpleInternal.sol, deployment/state/contracts.json, integrationTest/governance/governorTransferToken.ts
Max child transaction fix on vote
=> Max child transaction fix on vote

contracts/governance/GovernorCountingSimpleInternal.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, integrationTest/governance/governorTransferToken.ts
Max child transaction fix on vote
=> Max child transaction fix on vote 

contracts/governance/GovernorCountingSimpleInternal.sol, integrationTest/governance/GovernorMethods.ts, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
god token flag added to prevent subsequent claimed for any proposal.
=> god token flag added to prevent subsequent claimed for any proposal.

.github/workflows/execute-proposal.yml, proposalExecute.sh
proposal execution setup file added for github action
=> proposal execution setup file added for github action

contracts/governance/GovernorCountingSimpleInternal.sol, deployment/scripts/eventReader.ts, deployment/scripts/proposalScript.ts, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/Pair.ts, e2e-test/features/PairTest.feature, e2e-test/step-definitions/PairTest.ts, integrationTest/governance/GovernorMethods.ts, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
=> sync develop to main.

.github/workflows/execute-proposal.yml, deployment/scripts/proposalScript.ts, deployment/state/contracts.json, integrationTest/governance/GovernorMethods.ts
changes added for governor upgrade changes
=> changes added for governor upgrade changes

contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/GovernorTextProposal.sol, contracts/governance/GovernorTokenCreate.sol, contracts/governance/GovernorTransferToken.sol, contracts/governance/GovernorUpgrade.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, hardhat.config.ts, integrationTest/governance/GovernorMethods.ts, integrationTest/governance/governor.ts, integrationTest/governance/governorTextProposal.ts, integrationTest/governance/governorTransferToken.ts, integrationTest/governance/governorUpgrade.ts, test/governer-test.ts, utils/Helper.ts
=> synced with main.

cucumber.js
=> cloud report

contracts/LPToken.sol, contracts/common/BaseHTS.sol, contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/GovernorTokenCreate.sol, contracts/governance/GovernorTransferToken.sol, contracts/incentives/Vault.sol, test/governer-test.ts, test/pair-test.ts, test/vault-test.ts
=> Improve revert messages

e2e-test/step-definitions/PairTest.ts
=> small refactoring of tests

.github/workflows/e2e-test.yml
=> Skip on comment

.github/workflows/e2e-test.yml
=> changes for on pr merge

contracts/Pair.sol, deployment/state/contracts.json, integrationTest/factory.ts
Bug Fix of wrong Token transfer from Pair contract.
=> Bug fix of wrong Token transfer

e2e-test/business/Factory.ts, e2e-test/features/FactoryTest.feature, e2e-test/step-definitions/FactoryTest.ts
=> intial factory test

contracts/Factory.sol, deployment/state/contracts.json, hardhat.config.ts, integrationTest/factory.ts, test/pair-test.ts
Pairs in Factory are Proxy Addresses now.
=> proxy added to factory

contracts/Factory.sol, deployment/state/contracts.json, hardhat.config.ts, integrationTest/factory.ts, test/pair-test.ts
=> proxy added to factory (#174)

e2e-test/business/Factory.ts, e2e-test/features/FactoryTest.feature, e2e-test/step-definitions/FactoryTest.ts
=> factory tests

contracts/Factory.sol, contracts/ILPToken.sol, contracts/LPToken.sol, contracts/common/IERC20.sol, contracts/mock/ERC20Mock.sol, contracts/mock/MockBaseContract.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/Factory.ts, e2e-test/features/FactoryTest.feature, e2e-test/step-definitions/FactoryTest.ts, hardhat.config.ts, integrationTest/factory.ts, integrationTest/lpToken.ts, integrationTest/pair.ts, test/governer-test.ts, test/incentives-test.ts, test/pair-test.ts, test/vault-test.ts
Fixed lp token ownership smart contract
=> Fixed lp token ownership smart contract

.github/workflows/e2e-test.yml, e2e-test/business/Factory.ts, trigger-test.js
=> Us33998 fail GitHub action

deployment/scripts/initializeContracts.ts, deployment/service/ContractService.ts, deployment/state/contracts.json, deployment/state/contractsUAT.json
Script to initialise contracts
=> Script to initialise contracts

cucumber.js, e2e-test.sh, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/PairTest.ts
=> Sync main with develop

deployment/scripts/initializeContracts.ts, deployment/state/contracts.json, integrationTest/governance/GovernorMethods.ts
New governor contracts deployed and initialized.
=> New governor contracts deployed and initialised.

contracts/Pair.sol, deployment/state/contracts.json, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/PairTest.ts, integrationTest/factory.ts, integrationTest/pair.ts, test/pair-test.ts
Pair swap for hbar changes and  e2e test changes.
=> Pair swap hbar plus e2e check

contracts/governance/GovernorCountingSimpleInternal.sol, deployment/state/contracts.json, integrationTest/governance/GovernorMethods.ts, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
Calculate quorum threshold in terms of total GOD token supply
=> Calculate quorum threshold in terms of total GOD token supply

contracts/governance/GovernorCountingSimpleInternal.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, integrationTest/governance/GovernorMethods.ts, integrationTest/governance/governorTransferToken.ts, test/governer-test.ts
=> Sync develop to main

e2e-test.sh, e2e-test/business/Governor.ts, e2e-test/features/GovernorTransferToken.feature, e2e-test/step-definitions/GovernorTest.ts
=> Us33926 new proposal token transfer

contracts/Factory.sol, deployment/scripts/initializeContracts.ts, deployment/scripts/proposalPostExecutionScript.ts, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/Factory.ts, e2e-test/business/Pair.ts, integrationTest/factory.ts, integrationTest/governance/GovernorMethods.ts, utils/ContractMetadata.ts, utils/EventConsumer.ts
=> Proxy upgrade flow pair lptoken

deployment/state/contracts.json, integrationTest/governance/GovernorMethods.ts
New GodHolder deployed and initialised
=> new GodHolder deployed and initialised

.github/workflows/upgrade-proxy.yml
Deploy Job Manual trigger added
=> deploy contracts job updated to manual trigger

contracts/IPair.sol, contracts/Pair.sol, e2e-test/business/Pair.ts, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/PairTest.ts, integrationTest/pair.ts, test/pair-test.ts
**Description**
- Added slippage parameter to the `swapToken` Pair contract function. This is intended to support the user's ability to customize slippage values at the transaction level in the UI.
=> feat: Added custom slippage input for swapToken pair contract function

e2e-test.sh, e2e-test/business/Governor.ts, e2e-test/features/GovernorTransferToken.feature, e2e-test/step-definitions/GovernorTest.ts
=> E2e governor fix

contracts/Pair.sol
Contract HBAR balance dependency removed.
=> Contract HBAR balance dependency removed.

contracts/Pair.sol, e2e-test/business/Pair.ts, e2e-test/step-definitions/PairTest.ts, integrationTest/pair.ts, test/pair-test.ts
=> getSpotPrice function updated

contracts/Pair.sol, e2e-test/business/Common.ts, e2e-test/features/FactoryTest.feature, e2e-test/features/PairTest.feature, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/PairTest.ts, integrationTest/factory.ts, test/pair-test.ts
=> Us34047 new swap tests

.gitignore, contracts/Configuration.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/Configuration.ts, integrationTest/configuration.ts, test/configuration.ts
Added url keys under configuration
=> Added url keys under configuration

deployment/state/contractsUAT.json
Automatic proposal creation job fix
=> Automatic proposal creation job fix

e2e-test.sh, e2e-test/business/BaseHTS.ts, e2e-test/business/Common.ts, e2e-test/features/GovernorCreateToken.feature, e2e-test/step-definitions/GovernorCreateToken.ts
=> Us33927 create token proposal

hardhat.config.ts, test/configuration.ts, test/god-holder-test.ts, test/governer-test.ts, test/governor-token-dao.ts, test/incentives-test.ts, test/pair-test.ts
=> Code smell resolved

e2e-test.sh, e2e-test/business/Common.ts, e2e-test/business/Governor.ts, e2e-test/features/GovernorCreateToken.feature, e2e-test/features/GovernorTextProposal.feature, e2e-test/features/GovernorTransferToken.feature, e2e-test/step-definitions/GovernorContractUpgradeTest.ts, e2e-test/step-definitions/GovernorTextProposalTest.ts, package-lock.json, package.json
Us33933 governor text proposal
=> Us33933 governor text proposal

deployment/scripts/sendTokens.ts, e2e-test.sh, e2e-test/business/Common.ts, e2e-test/business/GovernorTokenDao.ts, e2e-test/features/DAOGovernorToken.feature, e2e-test/step-definitions/DAOGovernorToken.ts, e2e-test/step-definitions/GovernorTextProposalTest.ts
=> Us34086 governor token transfer dao

e2e-test/business/GovernorTokenDao.ts, e2e-test/features/DAOGovernorToken.feature, e2e-test/step-definitions/DAOGovernorToken.ts
=> dao governor token refactor

contracts/Factory.sol, contracts/LPToken.sol, contracts/Pair.sol, contracts/incentives/Splitter.sol, contracts/mock/ERC721Mock.sol, deployment/state/contracts.json, e2e-test/business/Factory.ts, hardhat.config.ts, integrationTest/factory.ts, test/pair-test.ts
=> Recommended pair for swap

contracts/Pair.sol
=> Made slippage absolute

.github/workflows/e2e-test.yml, contracts/dao/DAOFactory.sol, contracts/dao/GovernanceDAO.sol, contracts/dao/ITokenDAO.sol, contracts/dao/NFTDAOFactory.sol, e2e-test/business/GovernanceDAOFactory.ts, e2e-test/business/Governor.ts, test/governor-dao-factory-test.ts, test/nft-dao-factory-test.ts
=> Nft dao factory creation

contracts/Pair.sol, e2e-test/features/FactoryTest.feature, e2e-test/features/PairTest.feature, test/pair-test.ts
Pair with negative fee is not allowed
=> Pair with negative fee is not allowed

deployment/state/contracts.json, e2e-test/step-definitions/DAOGovernorToken.ts, e2e-test/step-definitions/GovernorContractUpgradeTest.ts, e2e-test/step-definitions/GovernorCreateToken.ts, e2e-test/step-definitions/GovernorTest.ts, e2e-test/step-definitions/GovernorTextProposalTest.ts
=> Fixed E2Es

contracts/ILPToken.sol, contracts/LPToken.sol, contracts/common/IERC20.sol, contracts/mock/ERC20Mock.sol, deployment/state/contracts.json, e2e-test/business/Common.ts, e2e-test/business/LpToken.ts, integrationTest/lpToken.ts, test/pair-test.ts
LP token security release changes
=> LP token security release changes

contracts/LPToken.sol, contracts/Pair.sol, contracts/common/TokenOperations.sol, contracts/gnosis/HederaGnosisSafe.sol, contracts/governance/GovernorCountingSimpleInternal.sol, deployment/state/contracts.json, e2e-test/business/Common.ts, integrationTest/factory.ts, integrationTest/lpToken.ts, integrationTest/pair.ts, test/governor-test.ts, test/multi-sig-dao-test.ts, test/pair-test.ts
Fixed swap functionality after v36 changes
=> Fixed swap functionality after v36 changes

.github/workflows/e2e-test.yml, e2e-test/business/Common.ts, e2e-test/features/DAOGovernorToken.feature, e2e-test/features/FactoryTest.feature, e2e-test/features/GovernorContractUpgrade.feature, e2e-test/features/GovernorCreateToken.feature, e2e-test/features/GovernorTextProposal.feature, e2e-test/features/GovernorTransferToken.feature, e2e-test/features/PairTest.feature, e2e-test/step-definitions/CommonSteps.ts, e2e-test/step-definitions/DAOGovernorToken.ts, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/GovernorContractUpgradeTest.ts, e2e-test/step-definitions/GovernorCreateToken.ts, e2e-test/step-definitions/GovernorTextProposalTest.ts, e2e-test/step-definitions/GovernorTransferTokenTest.ts, e2e-test/step-definitions/PairTest.ts
Us34142 governance refactor v2
=> Us34142 governance refactor v2

.github/workflows/slither-security-scan.yml
=> Us34191 slither GitHub action

contracts/Configuration.sol, contracts/Factory.sol, contracts/IPair.sol, contracts/Pair.sol, contracts/common/BaseHTS.sol, contracts/common/IBaseHTS.sol, contracts/mock/MockBaseContract.sol, contracts/mock/MockBaseHTSWithTokenCreationFail.sol, deployment/state/contracts.json, e2e-test/business/Configuration.ts, e2e-test/business/Pair.ts, integrationTest/configuration.ts, test/configuration.ts, test/pair-test.ts
=> Refactored Hbarx location

e2e-test/features/GovernorCreateToken.feature, e2e-test/step-definitions/GovernorCreateToken.ts
=> allowance and other changes in governance token create

contracts/Pair.sol, contracts/governance/GovernorTokenCreate.sol, test/governor-test.ts
=> Improved test coverage

.github/workflows/e2e-test.yml, e2e-test/business/factories/MultiSigDAOFactory.ts, e2e-test/features/GovernorCreateToken.feature, e2e-test/features/MultiSigDAO.feature, e2e-test/step-definitions/MultiSigDAOTest.ts
=> multisigdao factory e2e

contracts/ILPToken.sol, contracts/LPToken.sol, contracts/Pair.sol, deployment/state/contracts.json, e2e-test/business/LpToken.ts
Switch to uint from int as quantities cannot be negative
=> Switch to uint from int as quantities cannot be negative

contracts/LPToken.sol, contracts/Pair.sol, contracts/common/TokenOperations.sol, contracts/dao/GovernanceDAO.sol, contracts/dao/ITokenDAO.sol, contracts/gnosis/HederaGnosisSafe.sol, contracts/governance/GODHolder.sol, contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/GovernorTextProposal.sol, contracts/governance/GovernorTokenCreate.sol, contracts/governance/GovernorTransferToken.sol, contracts/governance/GovernorUpgrade.sol, contracts/governance/IGovernorTransferToken.sol, contracts/governance/NFTHolder.sol, e2e-test/business/Governor.ts, e2e-test/business/GovernorTokenDao.ts, test/governor-test.ts
Switch to uint from int as quantities cannot be negative
=> Governance -  Switch to uint from int as quantities cannot be negative

contracts/Factory.sol, contracts/Pair.sol, contracts/common/BaseHTS.sol, contracts/common/IBaseHTS.sol, contracts/common/TokenOperations.sol, contracts/governance/GovernorTokenCreate.sol, contracts/governance/NFTHolder.sol, contracts/mock/MockBaseContract.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/Governor.ts
Added guard checks before typecast
=> Added guard checks before typecast

deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/factories/DAOFactory.ts, integrationTest/dao/ftDaoFactory.ts
=> Fixing-logic-upgradation

e2e-test/business/FTDAO.ts, integrationTest/dao/ftDao.ts, integrationTest/dao/ftDaoFactory.ts
=> Token create via DAO

e2e-test/business/FTDAO.ts, integrationTest/dao/ftDao.ts, integrationTest/dao/ftDaoFactory.ts
=> Token create via DAO (#540)

contracts/dao/MultisigDAO.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/business/MultiSigDao.ts, integrationTest/dao/multiSigDAO.ts, test/multi-sig-dao-test.ts
=> Text proposal txn by multisig

contracts/Factory.sol, test/pair-test.ts
Fixed defect recommended pair for swap
=> Fixed defect recommended pair for swap

contracts/dao/FTDAO.sol, contracts/governance/GovernorUpgrade.sol, cucumber.js, deployment/scripts/createAndExecuteDAOProposals.ts, deployment/service/ContractService.ts, deployment/state/contractIds.json, deployment/state/contracts.json, e2e-test/business/Common.ts, e2e-test/business/FTDAO.ts, e2e-test/business/Factory.ts, e2e-test/business/Governor.ts, e2e-test/business/MultiSigDao.ts, e2e-test/business/Token.ts, e2e-test/business/factories/DAOFactory.ts, e2e-test/business/factories/TokenHolderFactory.ts, e2e-test/features/MultiSigDAO.feature, e2e-test/step-definitions/DAOGovernorToken.ts, e2e-test/step-definitions/DAONFTTokenTest.ts, e2e-test/step-definitions/FactoryTest.ts, e2e-test/step-definitions/MultiSigDAOTest.ts, integrationTest/dao/ftDaoFactory.ts, integrationTest/factory.ts, integrationTest/governance/governorTransferToken.ts, integrationTest/pair.ts, utils/AddressHelper.ts
=> attempted to fix testnet changes related issue

contracts/incentives/Vault.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, test/vault-test.ts
Vault staked token cannot be same as reward token
=> Vault staked token cannot be same as reward token

contracts/common/RoleBasedAccess.sol, contracts/dao/BaseDAO.sol, deployment/state/contractIds.json, deployment/state/contracts.json, deployment/state/contractsUAT.json, integrationTest/dao/ftDao.ts, integrationTest/dao/ftDaoFactory.ts, utils/deployContractOnTestnet.ts
=> Fix storage slot gaps

contracts/Configuration.sol, contracts/ILPToken.sol, contracts/LPToken.sol, contracts/Pair.sol, contracts/dao/MultisigDAO.sol, contracts/gnosis/HederaGnosisSafe.sol, contracts/governance/ITokenHolder.sol, contracts/governance/TokenHolder.sol, contracts/incentives/Vault.sol
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=VAU-04
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=MDA-02
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=HGS-01
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=NFH-01
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=CON-08
https://skyharbor.certik.com/report/609f50c5-5eb4-469e-8c73-7e7b456962a6?findingIndex=PAI-02
=> AuditFixMinors

contracts/incentives/Vault.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, test/vault-test.ts
Fixed inconsistent event emitted at the time of claim reward
=> Fixed inconsistent event emitted at the time of claim reward

contracts/Pair.sol, contracts/common/RoleBasedAccess.sol, contracts/dao/BaseDAO.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, e2e-test/features/FactoryTest.feature, e2e-test/step-definitions/FactoryTest.ts, test/pair-test.ts
Fixed audit comments from second round
=> Fixed audit comments from second round

contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/GovernorTransferToken.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, test/TestHelper.ts, test/governor-test.ts
Track active proposal balance for governor
=> Track active proposal balance for governor

contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/GovernorTransferToken.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, test/TestHelper.ts, test/governor-test.ts
Track active proposal balance for governor
=> Track active proposal balance for governor (#577)

contracts/gnosis/HederaGnosisSafe.sol, contracts/governance/TokenHolder.sol
=> Added storage gap

contracts/common/ISharedModel.sol, contracts/common/TokenOperations.sol, contracts/dao/FTDAO.sol, contracts/dao/FTDAOFactory.sol, contracts/dao/ISharedDAOModel.sol, contracts/dao/MultisigDAOFactory.sol, contracts/governance/GovernorCountingSimpleInternal.sol, contracts/governance/HederaGovernor.sol, contracts/governance/IGovernorBase.sol, contracts/governance/ITokenHolder.sol, contracts/governance/TokenHolder.sol, contracts/holder/AssetsHolder.sol, contracts/holder/IAssetsHolder.sol, contracts/mock/ERC721Mock.sol, contracts/mock/MockBaseContract.sol, contracts/mock/ProxyPatternMock.sol, contracts/mock/TokenHolderCallerMock.sol, package-lock.json, package.json, test/TestHelper.ts, test/assets-holder-test.ts, test/god-holder-test.ts, test/governor-dao-test.ts, test/nft-dao-factory-test.ts, test/nft-holder-test.ts, test/pair-test.ts, test/single-governor-test.ts
1. skipped 4 tests inside pair (Need to discuss before merge)
2. skipped 4 tests from old -governor (No need to fix there, we will remove the test file in last PR)
3. _associateToken inside unit test need to check if we can fix (coverage will be 100% then)
=> added sol file changes with unit test

contracts/Configuration.sol, contracts/LPToken.sol, contracts/Pair.sol, contracts/mock/MockLPToken.sol, contracts/mock/MockPair.sol, test/pair-test.ts
Disable logic contract initialization
=> Disable logic contract initialization

contracts/incentives/Splitter.sol, contracts/incentives/Vault.sol, test/TestHelper.ts, test/splitter-test.ts, test/vault-test.ts
Vault and splitter con04 changes
=> Addressed Vault and Splitter stop logic initialization changes.

contracts/Factory.sol, test/TestHelper.ts, test/pair-test.ts
=> Dex factory con04 changes

contracts/common/IERC721.sol, deployment/model/ApprovalForAll.ts, deployment/scripts/createNFTToken.ts, deployment/scripts/resetAllowance.ts, deployment/scripts/returnFT.ts, deployment/scripts/returnNft.ts, e2e-test/business/NFTToken.ts, e2e-test/features/FTGovernorNegative.feature, e2e-test/features/FTGovernorOthers.feature, e2e-test/features/NFTGovernorNegative.feature, e2e-test/features/NFTGovernorOthers.feature, e2e-test/step-definitions/HederaGovernorTest.ts, e2e-test/step-definitions/MultiSigDAOTest.ts, utils/ContractMetadata.ts, utils/MirrorNodeService.ts
=> attempted to fix e2e by resetting NFT token allowances

contracts/dao/FTDAOFactory.sol, deployment/state/contracts.json, deployment/state/contractsUAT.json, test/governor-dao-test.ts, test/nft-dao-factory-test.ts
=> fixed event data

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/build-and-test.yml, .github/workflows/deploy-contract-github.yml, .github/workflows/e2e-test.yml, .github/workflows/slither-security-scan.yml, .gitignore
- Configure to use self-hosted runner
- Name all steps
- Added Hardened Runner Step
- Pinned commits to actions
Fixes #636
=> ci: Updated for CI best practices

.github/CODEOWNERS, .github/workflows/build-and-test.yml, .github/workflows/deploy-contract-github.yml, .github/workflows/e2e-test.yml, .github/workflows/slither-security-scan.yml
Moves the self-hosted runner to the defi-dex-linux-medium runner group Updates the CODEOWNERS file to match the current standard
Fixes #648
=> ci: Update self hosted runner labels and CODEOWNERS

contracts/Configuration.sol, contracts/Factory.sol, contracts/ILPToken.sol, contracts/IPair.sol, contracts/LPToken.sol, contracts/Pair.sol, contracts/dao/BaseDAO.sol, contracts/dao/FTDAO.sol, contracts/dao/FTDAOFactory.sol, contracts/dao/MultisigDAO.sol, contracts/dao/MultisigDAOFactory.sol, contracts/dao/NFTDAOFactory.sol, contracts/gnosis/HederaGnosisSafe.sol, contracts/gnosis/HederaGnosisSafeProxyFactory.sol, contracts/gnosis/HederaMultiSend.sol, contracts/governance/GODHolder.sol, contracts/governance/GODTokenHolderFactory.sol, contracts/governance/HederaGovernor.sol, contracts/governance/ITokenHolder.sol, contracts/governance/ITokenHolderFactory.sol, contracts/governance/NFTHolder.sol, contracts/governance/NFTTokenHolderFactory.sol, contracts/governance/TokenHolder.sol, contracts/governance/TokenHolderFactory.sol, contracts/holder/AssetsHolder.sol, contracts/holder/IAssetsHolder.sol
This PR modifies the DEX contracts by adding documentation with every function explanation.
=> add documentation

.github/workflows/deploy-contract-github.yml, .github/workflows/e2e-test.yml
Updating github workflow actions to their step-security maintained version.
Fixes #659 
**Checklist**
=> ci: Updating actions to step-security version.
